// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Infix$BsRouter = require("../src/Infix.bs.js");
var Router$BsRouter = require("../src/Router.bs.js");
var Segment$BsRouter = require("../src/Segment.bs.js");

function idx(param) {
  return "Root";
}

function getUser(id, req) {
  return "Received request from " + (req.target + (" to fetch id: " + String(id)));
}

function searchUser(_name, _city, _req) {
  return "Search for user";
}

var router = Router$BsRouter.make(/* :: */[
      Infix$BsRouter.$neg$neg$great(Segment$BsRouter.nil, idx),
      /* :: */[
        Infix$BsRouter.$neg$neg$great(Infix$BsRouter.$slash$question((function (param) {
                    return Infix$BsRouter.$slash((function (param) {
                                  return Segment$BsRouter.s("user", param);
                                }), Segment$BsRouter.$$int, param);
                  }), Segment$BsRouter.nil), getUser),
        /* :: */[
          Infix$BsRouter.$neg$neg$great(Infix$BsRouter.$slash$question((function (param) {
                      return Infix$BsRouter.$slash((function (param) {
                                    return Infix$BsRouter.$slash((function (param) {
                                                  return Segment$BsRouter.s("user", param);
                                                }), Segment$BsRouter.str, param);
                                  }), Segment$BsRouter.str, param);
                    }), Segment$BsRouter.trail), searchUser),
          /* [] */0
        ]
      ]
    ]);

var req = {
  target: "/user/12"
};

var match = Router$BsRouter.match$prime("/some/url")(router);

if (match !== undefined) {
  Curry._1(match, req);
}

var match$1 = Router$BsRouter.match$prime("/user/12")(router);

if (match$1 !== undefined) {
  Curry._1(match$1, req);
}

var match$2 = Router$BsRouter.match$prime("/user/hello/world/")(router);

if (match$2 !== undefined) {
  Curry._1(match$2, req);
}

var match$3 = Router$BsRouter.match$prime("/user/hello/world")(router);

if (match$3 !== undefined) {
  Curry._1(match$3, req);
}

exports.idx = idx;
exports.getUser = getUser;
exports.searchUser = searchUser;
exports.router = router;
exports.req = req;
/* router Not a pure module */
