// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function make(label, from, to_) {
  return {
          from: from,
          label: label,
          to_: to_
        };
}

exports.make = make;
/* No side effect */
