// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Path$BsRouter = require("./Path.bs.js");

function $slash(m1, m2, r) {
  return Curry._1(m1, Curry._1(m2, r));
}

function $slash$question(m1, m2) {
  return Curry._1(m1, m2);
}

var $neg$neg$great = Path$BsRouter.make;

exports.$neg$neg$great = $neg$neg$great;
exports.$slash = $slash;
exports.$slash$question = $slash$question;
/* No side effect */
