// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Segment$BsRouter = require("./Segment.bs.js");

function make(r, handler) {
  return /* Path */[
          r,
          handler
        ];
}

function stringify(param) {
  return Segment$BsRouter.stringify(param[0]);
}

exports.make = make;
exports.stringify = stringify;
/* No side effect */
