// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Conv$BsRouter = require("./Conv.bs.js");

function pattern(label, from, to_, r) {
  return /* Conv */Block.__(2, [
            Conv$BsRouter.make(label, from, to_),
            r
          ]);
}

function s(w, r) {
  return /* Match */Block.__(1, [
            w,
            r
          ]);
}

function $$int(r) {
  return /* Conv */Block.__(2, [
            Conv$BsRouter.make(":int", Pervasives.int_of_string_opt, (function (prim) {
                    return String(prim);
                  })),
            r
          ]);
}

function str(r) {
  return /* Conv */Block.__(2, [
            Conv$BsRouter.make(":string", (function (x) {
                    return x;
                  }), (function (x) {
                    return x;
                  })),
            r
          ]);
}

function bool(r) {
  return /* Conv */Block.__(2, [
            Conv$BsRouter.make(":bool", Pervasives.bool_of_string_opt, Pervasives.string_of_bool),
            r
          ]);
}

function stringify$prime(param) {
  switch (param.tag | 0) {
    case /* End */0 :
        if (param[/* trailingSlash */0]) {
          return /* :: */[
                  "",
                  /* [] */0
                ];
        } else {
          return /* [] */0;
        }
    case /* Match */1 :
        return /* :: */[
                param[0],
                stringify$prime(param[1])
              ];
    case /* Conv */2 :
        return /* :: */[
                param[0].label,
                stringify$prime(param[1])
              ];
    
  }
}

function stringify(r) {
  var __x = stringify$prime(r);
  return Belt_List.reduce(__x, "", (function (acc, x) {
                return acc + ("/" + x);
              }));
}

var nil = /* End */Block.__(0, [/* trailingSlash */false]);

var trail = /* End */Block.__(0, [/* trailingSlash */true]);

exports.$$int = $$int;
exports.str = str;
exports.bool = bool;
exports.s = s;
exports.nil = nil;
exports.trail = trail;
exports.pattern = pattern;
exports.stringify = stringify;
/* No side effect */
