// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function splitPath(target) {
  var splitTarget = function (target) {
    switch (target) {
      case "" :
      case "/" :
          return /* [] */0;
      default:
        var xs = Belt_List.fromArray(target.split("/"));
        if (xs && xs[0] === "") {
          return xs[1];
        } else {
          return xs;
        }
    }
  };
  var i = "?".indexOf(target);
  if (i < 0) {
    return splitTarget(target);
  } else if (i !== 0) {
    return splitTarget(target.substring(0, i));
  } else {
    return /* [] */0;
  }
}

exports.splitPath = splitPath;
/* No side effect */
